# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: windows-latest

variables:
  buildConfiguration: 'Release'
  Version.MajorMinor: 5.0
  Version.Revision: $[counter(variables['Abbotware.Core'], 0)]  
  buildLabel3: "$(Version.MajorMinor).$(Version.Revision)"
  buildLabel4: "$(buildLabel3).0"

steps:
- task: PowerShell@2
  inputs:
    targetType: 'inline'
    script:  Write-Host "##vso[build.updatebuildnumber]$(buildLabel3)"

- checkout: self
  submodules: true
  persistCredentials: true

- task: UseDotNet@2
  inputs:
    useGlobalJson: true
  
- script: dotnet build --configuration $(buildConfiguration) /p:Version=$(buildLabel4) /p:AssemblyVersion=$(buildLabel4) /p:AssemblyInformationalVersion=$(buildLabel4) /p:FileVersion=$(buildLabel4) /p:PackageVersion=$(buildLabel3)
  displayName: 'dotnet build $(buildConfiguration)'

#- script: dotnet test --filter FullyQualifiedName~.UnitTests. /p:GeneratePackageOnBuild=false --configuration $(buildConfiguration) --no-restore --logger trx --collect:"XPlat Code Coverage" -- DataCollectionRunSettings.DataCollectors.DataCollector.Configuration.Format=cobertura
#  displayName: 'dotnet test $(buildConfiguration)'

- task: AWSPowerShellModuleScript@1
  inputs:
    awsCredentials: 'aws-unit-test'
    regionName: 'us-east-1'
    scriptType: 'inline'
    inlineScript: |
      dotnet test --filter FullyQualifiedName~.UnitTests. /p:GeneratePackageOnBuild=false --configuration $(buildConfiguration) --no-restore --logger trx --collect:"XPlat Code Coverage" -- DataCollectionRunSettings.DataCollectors.DataCollector.Configuration.Format=cobertura
  displayName: 'dotnet test $(buildConfiguration)'

- task: PublishTestResults@2
  displayName: 'Publish test report'
  inputs:
    testResultsFormat: VSTest
    testResultsFiles: '**/*.trx' 

- task: PublishCodeCoverageResults@1
  displayName: 'Publish code coverage report'
  inputs:
    codeCoverageTool: 'Cobertura'
    summaryFileLocation: '**/In/**/coverage.cobertura.xml'
- task: PublishBuildArtifacts@1
  displayName: 'Artifact: Nugets'
  inputs:
    pathToPublish: _Target/Release/nuget
    artifactName: Nugets

#- task: PublishBuildArtifacts@1
#  displayName: 'Artifact: Unit Test Report'
#  inputs:
#    pathToPublish: '**/*.trx'
#    artifactName: Trx

#- task: PublishBuildArtifacts@1
#  displayName: 'Artifact: Code Coverage Report'
#  inputs:
#    pathToPublish: '**/In/**/coverage.cobertura.xml'
#    artifactName: Cobertura

#- task: NuGetCommand@2
#  displayName: 'Publish Nuget'
#  inputs:
#    command: push
#    nuGetFeedType: internal
#    versioningScheme: byEnvVar
#    versionEnvVar: $(buildLabel3)
#    packagesToPush: ....
#    publishVstsFeed: ....
